library(testthat)
library(ForesToolboxRS)
library(stars)
library(raster)
library(rgdal)
library(forecast)

context("ForesToolboxRS::fusionRS")
test_that("fusionRS", {
  data("ForesToolboxRS_dataset")
  img <- brick(lapply(ForesToolboxRS_dataset$mosaic, '[[',1))
  img <- smootH(img)
  fusion <- fusionRS(x=img)
  expect_equal(max(raster::getValues(raster::mean(fusion[[1]]))),11.85757,tolerance=0.0001)
})
